version: 2

jobs:
  build_and_test:
    macos:
      xcode: "12.5"
    steps:
      - checkout
      - run: xcrun simctl list
      - run:
          name: Install build dependencies
          command: |
            sudo gem install xcpretty
            sudo gem install cocoapods -v 1.10.0
      - run:
          name: Fetch Cocoapods specs
          command: curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run: make install
      - run: make build
      - run: make test
      - run: make lint

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
